import bycrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bycrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bycrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "Ruby",
      slug: "ruby",
      category: "Igneous",
      image: "/images/ruby.jpg",
      price: 170,
      brand: "Fire",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        "a pink to blood-red colored gemstone, a variety of the mineral corundum (aluminium oxide). Other varieties of gem-quality corundum are called sapphires. Ruby is one of the traditional cardinal gems, together with amethyst, sapphire, emerald, and diamond.[3] The word ruby comes from ruber, Latin for red. The color of a ruby is due to the element chromium.",
    },
    {
      name: "Emerald",
      slug: "emerald",
      category: "Metamorphic",
      image: "/images/emerald.jpg",
      price: 130,
      brand: "Earth",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        "Emerald is a gemstone and a variety of the mineral beryl, colored green by trace amounts of chromium and/or sometimes vanadium. Beryl has a hardness of 7.5–8 on the Mohs scale. Emerald is one of the four recognized precious gemstones.",
    },
    {
      name: "Sapphire",
      slug: "sapphire",
      category: "Igneous",
      image: "/images/sapphire.jpg",
      price: 290,
      brand: "Water",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        "Sapphire is a precious gemstone, a variety of the mineral corundum, consisting of aluminium oxide with trace amounts of elements such as iron, titanium, chromium, vanadium, or magnesium. It is typically blue, but natural fancy sapphires also occur in yellow, purple, orange, and green colors",
    },
    {
      name: "Amethyst",
      slug: "amethyst",
      category: "Igneous",
      image: "/images/amethyst.jpg",
      price: 155,
      brand: "Wind",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description:
        "The ancient Greeks wore amethyst and carved drinking vessels from it in the belief that it would prevent intoxication. Amethyst is a semiprecious stone that is often used in jewelry and is the traditional birthstone for February.",
    },
    {
      name: "Opal",
      slug: "opal",
      category: "Metamorphic",
      image: "/images/opal.jpg",
      price: 110,
      brand: "Fire",
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Diamond",
      slug: "diamond",
      category: "Shirts",
      image: "/images/diamond.jpg",
      price: 300,
      brand: "Earth",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Tanzanite",
      slug: "tanzanite",
      category: "Pants",
      image: "/images/tanzanite.jpg",
      price: 230,
      brand: "Earth",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pair of pants",
    },
    {
      name: "Topaz",
      slug: "topaz",
      category: "Metamorphic",
      image: "/images/topaz.jpg",
      price: 100,
      brand: "Water",
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Garnet",
      slug: "garnet",
      category: "Metamorphic",
      image: "/images/garnet.jpg",
      price: 7120,
      brand: "Fire",
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Pearl",
      slug: "pearl",
      category: "Sedimentary",
      image: "/images/pearl.jpg",
      price: 300,
      brand: "Water",
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Moonstone",
      slug: "Moonstone",
      category: "Sedimentary",
      image: "/images/moonstone.jpg",
      price: 210,
      brand: "Water",
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Peridot",
      slug: "peridot",
      category: "Metamorphic",
      image: "/images/peridot.jpg",
      price: 90,
      brand: "Wind",
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Onyx",
      slug: "onyx",
      category: "Igneous",
      image: "/images/onyx.jpg",
      price: 70,
      brand: "Earth",
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
};

export default data;
